add shellcheck to test harness and fix shellcheck offenses

diff --git a/builder/build b/builder/build
--- a/builder/build
+++ b/builder/build
@@ -1,8 +1,26 @@
 #!/bin/bash
 set -e
 set -x
+set -o pipefail
 
+################################################################################
+# Build and install Duo Authproxy.
+#
 # https://duo.com/support/documentation/authproxy_reference#installation
+################################################################################
+
+finish() {
+  declare -ri RC=$?
+
+  if [ ${RC} -eq 0 ]; then
+    echo "$0" OK >&2
+  else
+    echo "$0" failed with exit code ${RC} >&2
+    exit ${RC}
+  fi
+}
+
+trap finish EXIT
 
 # Build and install authproxy.
 cd /root
@@ -33,7 +51,8 @@ tar xzf asn1crypto.tgz
 
 popd
 
-export PYTHON=$(which python)
+PYTHON="$(which python)"
+declare -rx PYTHON
 make
 cd duoauthproxy-build
 ./install --install-dir=/opt/duoauthproxy --service-user=duo --create-init-script=yes
diff --git a/ci/licenses b/ci/licenses
--- a/ci/licenses
+++ b/ci/licenses
@@ -1,22 +1,24 @@
 #!/bin/bash
 set -e
 set -u
+set -o pipefail
+
+################################################################################
+# Show licenses using the same commands as in README.
+# If these commands fail, the build aborts.
+# Thus you should update these commands and the README.
+################################################################################
 
 . ci/functions.sh
 
-# Show licenses using the same commands as in README.
-# If either of these commands fails, the build aborts.
-# Thus you should update these commands and the README.
-eula='/opt/duoauthproxy/doc/eula-linux.txt'
-dir='/root/duoauthproxy-*-src'
 echo
 echo '==== Duo licenses ===='
 # Note: This shows the Duo EULA as well as the open-source licenses
 # of the various 3rd-party components used in the proxy.
-dir='/opt/duoauthproxy/doc/'
-smitty docker run --rm -it --entrypoint sh duoauthproxy -c "find $dir -type f -exec cat {} +"
+declare -r eula_dir='/opt/duoauthproxy/doc/'
+smitty docker run --rm -it --entrypoint sh duoauthproxy -c "find ${eula_dir} -type f -exec cat {} +"
 echo
 echo '==== List of 3rd-party licenses ===='
 # This one is just for completeness.
-dir='/root/duoauthproxy-*-src'
-smitty docker run --rm -it --entrypoint sh duoauthproxy-builder -c "find $dir -iname '*license*'"
+declare -r third_party_dir='/root/duoauthproxy-*-src'
+smitty docker run --rm -it --entrypoint sh duoauthproxy-builder -c "find ${third_party_dir} -iname '*license*'"
diff --git a/runtime/harden b/runtime/harden
--- a/runtime/harden
+++ b/runtime/harden
@@ -1,7 +1,8 @@
 #!/bin/sh
 set -x
 set -e
-#
+set -o pipefail
+################################################################################
 # Docker build calls this script to harden the image during build.
 #
 # NOTE: To build on CircleCI, you must take care to keep the `find`
@@ -11,6 +12,20 @@ set -e
 #    lxc-start: The container failed to start.
 #    lxc-start: Additional information can be obtained by \
 #        setting the --logfile and --logpriority options.
+################################################################################
+
+finish() {
+  readonly RC=$?
+
+  if [ ${RC} -eq 0 ]; then
+    echo "$0" OK >&2
+  else
+    echo "$0" failed with exit code ${RC} >&2
+    exit ${RC}
+  fi
+}
+
+trap finish EXIT
 
 # Remove existing crontabs, if any.
 rm -fr /var/spool/cron
@@ -22,7 +37,7 @@ find /sbin /usr/sbin ! -type d \
   -a ! -name nologin \
   -delete
 
-sysdirs="
+readonly sysdirs="
   /bin
   /etc
   /lib
@@ -35,22 +50,32 @@ sysdirs="
 # Normally, I'd do this on the root fs, but circle ci fails with:
 #   chmod: /dev/mqueue: Operation not permitted
 # Therefore restrict the find to sysdirs listed above.
-find $sysdirs -xdev -type d -perm +0002 -exec chmod o-w {} +
-find $sysdirs -xdev -type f -perm +0002 -exec chmod o-w {} +
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type d -perm +0002 -exec chmod o-w {} +
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type f -perm +0002 -exec chmod o-w {} +
 
 # Remove crufty...
 #   /etc/shadow-
 #   /etc/passwd-
 #   /etc/group-
-find $sysdirs -xdev -type f -regex '.*-$' -exec rm -f {} +
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type f -regex '.*-$' -exec rm -f {} +
 
 # Ensure system dirs are owned by root and not writable by anybody else.
-find $sysdirs -xdev -type d \
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type d \
   -exec chown root:root {} \; \
   -exec chmod 0755 {} \;
 
 # Remove all suid files.
-find $sysdirs -xdev -type f -a -perm +4000 -delete
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type f -a -perm +4000 -delete
 
 # Remove init scripts since we do not use them.
 rm -fr /etc/init.d
@@ -74,7 +99,9 @@ rm -fr /root
 rm -f /etc/fstab
 
 # Remove broken symlinks (because we removed the targets above).
-find $sysdirs -xdev -type l -exec test ! -e {} \; -delete
+#
+# shellcheck disable=SC2086
+find ${sysdirs} -xdev -type l -exec test ! -e {} \; -delete
 
 # Remove unnecessary user accounts.
 sed -i -r '/^(duo)/!d' /etc/group
